FROM unicon/shibboleth-idp

MAINTAINER jason.umiker@gmail.com

ADD init-idp.sh /usr/local/bin
ADD shibboleth-idp/ /opt/shibboleth-idp/
ADD jetty-home/ /opt/jetty-home/
ADD shib-jetty-base/ /opt/shib-jetty-base/
