FROM unicon/shibboleth-idp

MAINTAINER jason.umiker@gmail.com

ADD run-jetty.sh /usr/local/bin
ADD jetty-home/ /opt/jetty-home/
ADD shib-jetty-base/ /opt/shib-jetty-base/

RUN cd /tmp
RUN curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
RUN python get-pip.py
RUN pip install awscli --upgrade
RUN curl -L "https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64" -o /usr/local/bin/jq
RUN chmod +x /usr/local/bin/jq
